name: rp2
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.9.9=h06a4308_0
  - expat=2.7.1=h6a678d5_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libmpdec=4.0.0=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - lz4-c=1.9.4=h6a678d5_1
  - ncurses=6.5=h7934f7d_0
  - openssl=1.1.1w=h7f8727e_0
  - pip=25.2=pyhc872135_1
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.10.0=h12debd9_5
  - readline=8.3=hc2a1206_0
  - setuptools=80.9.0=py310h06a4308_0
  - sqlite=3.50.2=hb25bd0a_1
  - tk=8.6.15=h54e0aa7_0
  - wheel=0.45.1=py310h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.7=h11fc155_0
  - pip:
      - absl-py==2.1.0
      - annotated-types==0.7.0
      - astunparse==1.6.3
      - attrs==25.4.0
      - bsuite==0.3.5
      - cachetools==5.5.0
      - certifi==2024.8.30
      - cffi==1.17.1
      - charset-normalizer==3.3.2
      - click==8.1.8
      - cloudpickle==3.0.0
      - contourpy==1.1.1
      - cycler==0.12.1
      - cython==0.29.37
      - dm-env==1.6
      - dm-tree==0.1.9
      - docker-pycreds==0.4.0
      - eval-type-backport==0.2.2
      - farama-notifications==0.0.4
      - fasteners==0.19
      - filelock==3.15.4
      - flatbuffers==25.9.23
      - fonttools==4.53.1
      - frozendict==2.4.6
      - fsspec==2024.6.1
      - gast==0.6.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - glfw==2.7.0
      - google-auth==2.34.0
      - google-auth-oauthlib==1.0.0
      - google-pasta==0.2.0
      - graphviz==0.20.3
      - grpcio==1.66.1
      - gym==0.26.2
      - gym-notices==0.0.8
      - gymnasium==1.2.1
      - h5py==3.15.1
      - highway-env==1.9.1
      - idna==3.8
      - imageio==2.37.0
      - imageio-ffmpeg==0.5.1
      - importlib-metadata==8.2.0
      - importlib-resources==6.4.0
      - jax-jumpy==1.0.0
      - jinja2==3.1.4
      - joblib==0.14.1
      - keras==3.11.3
      - kiwisolver==1.4.5
      - lazy-loader==0.4
      - libclang==18.1.1
      - markdown==3.7
      - markdown-it-py==4.0.0
      - markupsafe==2.1.5
      - matplotlib==3.10.7
      - mdurl==0.1.2
      - minigrid==3.0.0
      - mizani==0.14.2
      - ml-dtypes==0.5.3
      - mpmath==1.3.0
      - mujoco-py==2.1.2.14
      - namex==0.1.0
      - networkx==3.1
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.6.20
      - nvidia-nvtx-cu12==12.1.105
      - oauthlib==3.2.2
      - opencv-python==4.10.0.84
      - opt-einsum==3.4.0
      - optree==0.17.0
      - packaging==24.1
      - pandas==2.3.3
      - patsy==1.0.1
      - pillow==10.4.0
      - platformdirs==4.3.6
      - plotnine==0.15.0
      - popgym==1.0.6
      - protobuf==6.33.0
      - psutil==6.0.0
      - pyasn1==0.6.0
      - pyasn1-modules==0.4.0
      - pycolab==1.2
      - pycparser==2.22
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pygame==2.6.1
      - pygments==2.19.2
      - pyparsing==3.1.2
      - python-dateutil==2.9.0.post0
      - pytz==2024.1
      - pyyaml==6.0.2
      - requests==2.32.3
      - requests-oauthlib==2.0.0
      - rich==14.2.0
      - rpm==0.4.0
      - rsa==4.9
      - scikit-image==0.25.2
      - scipy==1.15.3
      - seaborn==0.13.2
      - sentry-sdk==2.22.0
      - setproctitle==1.3.5
      - six==1.16.0
      - smmap==5.0.2
      - statsmodels==0.14.5
      - sympy==1.13.2
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.20.0
      - termcolor==3.1.0
      - tifffile==2025.5.10
      - torch==2.4.1
      - triton==3.0.0
      - typing-extensions==4.12.2
      - typing-inspection==0.4.2
      - tzdata==2024.1
      - urllib3==2.2.2
      - wandb==0.22.2
      - werkzeug==3.0.4
      - wrapt==1.17.3
      - xmltodict==0.13.0
      - zipp==3.20.0
prefix: /home/geraudnt/miniconda3/envs/rp2
